apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-btc-bot
  namespace: tg-btc-bot
  labels:
    app: tg-btc-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-btc-bot
  template:
    metadata:
      labels:
        app: tg-btc-bot
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: tg-btc-bot
        image: ghcr.io/pavelkv94/tg-btc-assistant_bot:latest
        imagePullPolicy: Always
        env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: tg-bot-secrets
              key: BOT_TOKEN
        - name: COINMARKET_API_KEY
          valueFrom:
            secretKeyRef:
              name: tg-bot-secrets
              key: COINMARKET_API_KEY
        - name: NAVIDROME_URL
          valueFrom:
            configMapKeyRef:
              name: tg-bot-config
              key: NAVIDROME_URL
        volumeMounts:
        - name: json-storage
          mountPath: /app/json_db
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: json-storage
        persistentVolumeClaim:
          claimName: tg-bot-pvc