# apiVersion: v1
# kind: Service
# metadata:
#   name: tg-btc-bot
#   namespace: tg-btc-bot
# spec:
#   selector:
#     app: tg-btc-bot
#   ports:
#   - port: 3000
#     targetPort: 3000
#   type: ClusterIP